### ISSUE TITLE
Mercurius explain graphiql improvement

### ISSUE THREAD

**Issue by codeflyer** [nearform/mercurius-explain-graphiql-plugin#16]
Update the graphiql plugin

- [x] Refactor the response from an Array to On object
- [x] Do not remove the extensions values from the `result` panel
- [x] Add a column in the result that shows the full time spent in a `path`. The velua is the time spend from the `begin` value of the `node` to the last of the `end` values of the children.
- [x] Add an SVG icon instead of the `string`
- [x] Verify that the icon is centered when integrated with mercurius.

## Refactor the response from an Array to an object

The result is now returned as array in the `explain` attribute.

The new structure should be

```
{
   extensions: {
      explain: {
         profiler: {
            data: [....]
         }
      }
   }
}
```

**Comment by brunopascottini** [comment]
Closing as all items of the list are completed.
